server:
  port: 8010
spring:
  application:
    name: discovery-service
  config:
    import: optional:configserver:http://localhost:8012
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka