server:
  port: 8010
spring:
  application:
    name: discovery-service
  security:
    user:
      name: test
      password: test
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka