server:
  port: 8012
spring:
  profiles:
    active: native
  application:
    name: api-config-server
  cloud:
    config:
      server:
        native:
          search-locations: C:\dev\projects\SpringCloudConfiguration
        git:
          uri: https://github.com/alexn256/SpringCloudConfiguration
          username: alexn256
          password:
          clone-on-start: true
          default-label: main
          ignore-local-ssh-settings: true
    bus:
      enabled: true
      refresh:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
